name: appdressbook
description: "Address Book app that synchronizes contacts using a custom API server."
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  flutter_spinkit: ^5.2.1
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  crypto: ^3.0.6
  get_it: ^8.0.3
  internet_connection_checker_plus: ^2.7.1
  dart_jsonwebtoken: ^3.2.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/img/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/img/logo.png"
  windows:
    generate: true
    image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.env_production
    - assets/.env_development
    - assets/i18n/
    - assets/img/
    - assets/docs/