// Copyright (c) 2020 Davide Gironi
// Please refer to LICENSE file for licensing information.

// load settings
import Config from '../config/config';

/**
 * themers
 */
const themes = {
  // default theme
  default: {
    COLOR_BACKGROUND: '#ffffff',
    COLOR_BUTTON: '#ffb06b',
    COLOR_BUTTONTEXT: '#000000',
    COLOR_SPLASHBACKGROUND: '#ffb06b',
    COLOR_NAVBACKGROUND: '#ffb06b',
    COLOR_NAVHEADER: '#000000',
    COLOR_TEXTINPUTBACKGROUND: '#ffebd9',
    COLOR_TEXTINPUTPLACEHOLDER: '#737373',
    COLOR_TEXTINPUT: '#000000',
    COLOR_SETTINGSHEADER: '#ffe1c7',
    COLOR_SETTINGSHEADERBORDER: '#ffb06b',
    COLOR_TEXTLOGINTITLE: '#212121',
    COLOR_ADDRESSBOOKLISTBACK: '#ffffff',
    COLOR_ADDRESSBOOKSEARCHINPUT: '#ffe1c7',
    COLOR_ADDRESSBOOKSEARCHBAR: '#ffe1c7',
    COLOR_ADDRESSBOOKSEARCHBARBORDER: '#ffb06b',
    COLOR_ADDRESSBOOKLETTERBACK: '#ffffff',
    COLOR_ADDRESSBOOKLETTERBORDER: '#d6d6d6',
    COLOR_ADDRESSBOOKCONTACTPRESS: '#f7ff93',
    COLOR_ADDRESSBOOKLATESTCONTACTBACK: '#ffffff',
    COLOR_ADDRESSBOOKLETTERPRESS: '#f7ff93',
    COLOR_ADDRESSBOOKCANCELPRESS: '#ffe1c7',
    COLOR_ADDRESSBOOKHIGHLIGHTNAME: '#6183ff',
    COLOR_ADDRESSBOOKROLEINFO: '#444444',
    COLOR_ADDRESSBOOKCONTACTPRESSCONTACT: '#f7ff93',
    COLOR_ADDRESSBOOKCONTACTINFOTEXT: '#212121',
    COLOR_ADDRESSBOOKCONTACTSECTIONBORDER: '#d6d6d6'
  }
};

/**
 * export the selected theme
 */
export default themes[Config.theme];
